// Literal Tailwind recipes shared by component markers and their interactive states.
// These are utility classes, not CSS rules; Tailwind compiles them at build time.
export const uiClasses: Readonly<Record<string, string>> = {
  $body: [
    '[:where(&)]:bg-[#f6fbff] [:where(&)]:text-[color:#081b2d] [:where(&)]:[font-family:"Plus_Jakarta_Sans",_system-ui,_sans-serif] [:where(&)]:[transition:background-color_300ms_ease,_color_300ms_ease]',
    '[:where(&)_::selection]:bg-[#bcecff] [:where(&)_::selection]:text-[color:#081b2d]',
    "[[data-theme='dark']_:where(&)]:[background:#050b1a] [[data-theme='dark']_:where(&)]:text-[color:#eef7ff]",
    "[:where(&)_[data-theme='dark']_input]:[color-scheme:dark]",
    "[:where(&)_[data-theme='dark']_select]:[color-scheme:dark]",
    "[:where(&)_[data-theme='dark']_textarea]:[color-scheme:dark]",
  ].join(' '),
  $html: [
    '[:where(&)]:[-webkit-font-smoothing:antialiased] [:where(&)]:[-moz-osx-font-smoothing:grayscale] [:where(&)]:scroll-smooth',
    'reduce-motion:[:where(&)]:!scroll-auto',
  ].join(' '),
  absolute: ['[.chapter-resale_>_div&]:hidden', '[.chapter-organizers_>_div&]:hidden'].join(' '),
  active: [
    'legacy:[.nav-inner_>_a&]:text-accent legacy:[.nav-inner_>_a&]:[border-bottom-color:var(--accent)]',
  ].join(' '),
  'art-bottom': [
    'legacy:[&.art-bottom]:flex legacy:[&.art-bottom]:justify-between legacy:[&.art-bottom]:text-[length:9px] legacy:[&.art-bottom]:tracking-[0.06em]',
    'legacy:until-760:[&.art-bottom]:text-[length:7px]',
  ].join(' '),
  'art-clay': [
    'legacy:[&.art-clay]:[background:#e7d9c0] legacy:[&.art-clay]:text-[color:#5c3525]',
  ].join(' '),
  'art-court': [
    'legacy:[&.art-court]:[background:#df5935] legacy:[&.art-court]:text-[color:#24180f]',
  ].join(' '),
  'art-forest': [
    'legacy:[&.art-forest]:[background:linear-gradient(130deg,_#1c453b,_#3f7151)] legacy:[&.art-forest]:text-[color:#e3e8bd]',
  ].join(' '),
  'art-kicker': [
    'legacy:[&.art-kicker]:text-[length:8px] legacy:[&.art-kicker]:font-bold legacy:[&.art-kicker]:tracking-[0.16em]',
    'legacy:until-760:[&.art-kicker]:text-[length:6px]',
  ].join(' '),
  'art-motion': [
    'legacy:[&.art-motion]:[background:#29203e] legacy:[&.art-motion]:text-[color:#f2c9c3]',
    'legacy:[&.art-motion_>_strong]:[font-family:Georgia,_serif] legacy:[&.art-motion_>_strong]:[font-style:italic] legacy:[&.art-motion_>_strong]:font-normal',
  ].join(' '),
  'art-ocean': [
    'legacy:[&.art-ocean]:[background:radial-gradient(ellipse_at_80%_15%,_#5bd1d4,_transparent_55%),_linear-gradient(140deg,_#154564,_#057486)]',
  ].join(' '),
  'art-pmc': [
    'legacy:[&.art-pmc]:[background:linear-gradient(135deg,_#cdcdf2,_#eecee4)] legacy:[&.art-pmc]:text-[color:#373258]',
  ].join(' '),
  'art-shape': [
    'legacy:[&.art-shape]:absolute legacy:[&.art-shape]:w-[180px] legacy:[&.art-shape]:h-[180px] legacy:[&.art-shape]:[border:1px_solid_#ffffff60] legacy:[&.art-shape]:rounded-full legacy:[&.art-shape]:top-[15%] legacy:[&.art-shape]:right-[-3%] legacy:[&.art-shape]:z-[-1]',
    'legacy:[.art-ocean_&.art-shape]:w-[340px] legacy:[.art-ocean_&.art-shape]:h-[90px] legacy:[.art-ocean_&.art-shape]:[transform:rotate(-25deg)] legacy:[.art-ocean_&.art-shape]:top-[45%] legacy:[.art-ocean_&.art-shape]:right-[-20%] legacy:[.art-ocean_&.art-shape]:shadow-[0_15px_0_#ffffff15,_0_30px_0_#ffffff10]',
    'legacy:[.art-court_&.art-shape]:[border:3px_solid_#391c16] legacy:[.art-court_&.art-shape]:[background:repeating-linear-gradient(90deg,_transparent_0_58px,_#391c16_58px_60px)] legacy:[.art-court_&.art-shape]:[transform:rotate(25deg)] legacy:[.art-court_&.art-shape]:right-[-20px]',
    'legacy:[.art-motion_&.art-shape]:[border:24px_solid_#bc839f] legacy:[.art-motion_&.art-shape]:rounded-[45%_55%_70%_30%] legacy:[.art-motion_&.art-shape]:[transform:rotate(-40deg)] legacy:[.art-motion_&.art-shape]:right-[-10px] legacy:[.art-motion_&.art-shape]:top-[-20px]',
    'legacy:[.art-clay_&.art-shape]:[background:linear-gradient(90deg,_#8d4e36,_#c68458_40%,_#8d4e36)] legacy:[.art-clay_&.art-shape]:rounded-[30%_30%_45%_45%] legacy:[.art-clay_&.art-shape]:w-[115px] legacy:[.art-clay_&.art-shape]:h-[145px] legacy:[.art-clay_&.art-shape]:right-[15px] legacy:[.art-clay_&.art-shape]:top-[24%] legacy:[.art-clay_&.art-shape]:border-0',
    'legacy:[.art-forest_&.art-shape]:rounded-[100%_0] legacy:[.art-forest_&.art-shape]:[background:#8da86770] legacy:[.art-forest_&.art-shape]:[transform:rotate(-15deg)] legacy:[.art-forest_&.art-shape]:shadow-[-45px_65px_0_#82a86150]',
    'legacy:[.art-pmc_&.art-shape]:[border:20px_solid_#ffffff75] legacy:[.art-pmc_&.art-shape]:[transform:rotate(-25deg)] legacy:[.art-pmc_&.art-shape]:w-[170px] legacy:[.art-pmc_&.art-shape]:h-[105px] legacy:[.art-pmc_&.art-shape]:top-[20%]',
    'legacy:[.event-art.has-photo_&.art-shape]:hidden',
  ].join(' '),
  'article-list': ['legacy:grid legacy:gap-5 legacy:mt-[30px]'].join(' '),
  'bg-[radial-gradient(circle_at_85%_45%,rgba(232,93,44,0.45),transparent_34%)]': [
    '[.chapter-merchandise_&]:opacity-[0.2]',
  ].join(' '),
  'bg-emerald-100': ['[.reference-site.reference-site_&]:text-[color:#065f46]'].join(' '),
  'bg-ink-100': [
    "[[data-theme='dark']_&]:!bg-[#101c35]",
    '[.reference-site.reference-site_&]:!bg-home-elevated',
  ].join(' '),
  'bg-ink-50': [
    "[[data-theme='dark']_&]:!bg-[#081126]",
    '[.reference-site.reference-site_&]:!bg-home-page',
  ].join(' '),
  'bg-rose-100': ['[.reference-site.reference-site_&]:text-[color:#9f1239]'].join(' '),
  'bg-white': ["[[data-theme='dark']_&]:!bg-[#0d1730]"].join(' '),
  'border-ink-100': ["[[data-theme='dark']_&]:![border-color:#203455]"].join(' '),
  'border-ink-200': ["[[data-theme='dark']_&]:![border-color:#203455]"].join(' '),
  'border-t': [
    '[.reference-site.reference-site_article_&]:gap-3 [.reference-site.reference-site_article_&]:flex-wrap',
    '[.chapter-resale_article_&]:mt-[auto]',
  ].join(' '),
  brand: [
    'legacy:inline-flex legacy:items-center legacy:gap-2 legacy:whitespace-nowrap legacy:text-[length:23px] legacy:font-extrabold legacy:tracking-[-1.2px]',
    'legacy:until-760:text-[length:20px]',
    'legacy:until-370:text-[length:17px]',
  ].join(' '),
  'brand-dot': ['legacy:text-accent'].join(' '),
  'brand-light': ['legacy:[font-weight:450]'].join(' '),
  'brand-mark': [
    'relative inline-flex w-[38px] h-[38px] items-center justify-center text-[color:#ffffff] [background:linear-gradient(145deg,_#38bdf8,_#0284c7)] [border:1px_solid_rgba(255,_255,_255,_0.28)] rounded-[13px_13px_13px_5px] shadow-[0_8px_18px_rgba(2,_132,_199,_0.28)] [transform:rotate(-4deg)] [transition:transform_200ms_ease,_box-shadow_200ms_ease]',
    '[.brand-lockup:hover_&]:[transform:rotate(0deg)_translateY(-1px)] [.brand-lockup:hover_&]:shadow-[0_10px_24px_rgba(2,_132,_199,_0.36)]',
    '[.reference-site.reference-site_&]:transform-none',
    '[.reference-site.reference-site_.brand-lockup:hover_&]:transform-none',
    'legacy:grid legacy:place-items-center legacy:w-8 legacy:h-8 legacy:[background:var(--accent)] legacy:text-on-accent legacy:rounded-[10px] legacy:[transform:rotate(-8deg)]',
    'legacy:until-760:w-7 legacy:until-760:h-7',
    'legacy:until-370:hidden',
  ].join(' '),
  'brand-mark-dot': [
    'absolute right-[-4px] bottom-[-3px] w-2.5 h-2.5 [background:#dff6ff] [border:3px_solid_#0284c7] rounded-[999px]',
    "[[data-theme='dark']_&]:[background:#0d1730] [[data-theme='dark']_&]:[border-color:#38bdf8]",
  ].join(' '),
  breadcrumb: [
    'legacy:text-muted legacy:text-[length:12px] legacy:mb-[25px] legacy:flex legacy:gap-3',
  ].join(' '),
  button: [
    'legacy:inline-flex legacy:justify-center legacy:items-center legacy:gap-3 legacy:min-h-12 legacy:[border:1px_solid_transparent] legacy:rounded-[var(--radius-sm)] legacy:[background:var(--accent)] legacy:text-on-accent legacy:text-[length:14px] legacy:[font-weight:650] legacy:p-[13px_21px] legacy:[transition:background_0.2s]',
    'legacy:[&:hover]:[background:var(--accent-hover)]',
    'legacy:[.reading-page_&]:mt-5',
    'legacy:[.product-card_&]:w-full',
    'legacy:until-760:[.header-actions_>_&]:hidden',
    'legacy:[.hero-search_&]:shrink-0',
    'legacy:until-900:[.hero-search_&]:flex-[1]',
    'legacy:until-760:[.hero-search_&]:basis-[100%]',
  ].join(' '),
  'button-outline': [
    'legacy:[&.button-outline]:[background:transparent] legacy:[&.button-outline]:border-line legacy:[&.button-outline]:text-foreground',
    'legacy:[&.button-outline:hover]:[background:var(--accent-soft)]',
  ].join(' '),
  'button-small': [
    'legacy:[&.button-small]:min-h-10 legacy:[&.button-small]:p-[10px_15px] legacy:[&.button-small]:text-[length:12px]',
  ].join(' '),
  'card-arrow': [
    'legacy:grid legacy:place-items-center legacy:w-8 legacy:h-8 legacy:rounded-full legacy:[background:var(--surface-raised)] legacy:text-accent',
    'legacy:until-760:w-[26px] legacy:until-760:h-[26px]',
  ].join(' '),
  'card-bottom': [
    'legacy:flex legacy:items-center legacy:justify-between legacy:pt-[13px] legacy:[border-top:1px_solid_var(--line)] legacy:text-[length:12px]',
    'legacy:[&_strong]:text-[length:16px] legacy:[&_strong]:text-accent legacy:[&_strong]:ml-[3px]',
    'legacy:until-760:gap-[5px]',
    'legacy:until-760:[&_strong]:text-[length:14px] legacy:until-760:[&_strong]:ml-[0]',
    'legacy:[.reopening-body_&]:flex-wrap legacy:[.reopening-body_&]:gap-3',
  ].join(' '),
  'catalog-floating': [
    '[&_a]:rounded-[100px] [&_a]:px-[18px] [&_a]:min-h-11',
    '[transition:opacity_420ms_ease,_translate_680ms_cubic-bezier(0.22,_1,_0.36,_1),_scale_680ms_cubic-bezier(0.22,_1,_0.36,_1),_visibility_0s_linear_680ms]',
    '[.reference-site.reference-site_&_>_div]:[background:var(--home-nav)] [.reference-site.reference-site_&_>_div]:border-home-line [.reference-site.reference-site_&_>_div]:rounded-[18px] [.reference-site.reference-site_&_>_div]:shadow-[0_10px_40px_#0003]',
    'until-639:[.reference-site.reference-site_&]:hidden',
  ].join(' '),
  'category-label': [
    'legacy:text-[length:10px] legacy:text-accent legacy:font-bold',
    'legacy:until-760:text-[length:9px]',
  ].join(' '),
  'category-nav': [
    'legacy:[border-top:1px_solid_var(--line)]',
    'legacy:until-760:hidden',
    'legacy:[.home-header_&]:hidden',
  ].join(' '),
  'chapter-blog': [
    '![background:var(--home-elevated)]',
    '[&_article:first-child]:row-[span_2]',
    '[&_article:not(:first-child)]:grid [&_article:not(:first-child)]:grid-cols-[38%_minmax(0,_1fr)]',
    '[&_article:not(:first-child)_>_div:first-child]:aspect-[auto] [&_article:not(:first-child)_>_div:first-child]:h-full',
    '[&_article:first-child_h3]:text-[length:24px]',
    'until-959:[&_article:not(:first-child)]:block',
    'until-959:[&_article:not(:first-child)_>_div:first-child]:h-40',
    'until-639:[&_article:first-child]:row-[auto]',
    'until-639:[&_article:not(:first-child)_>_div:first-child]:h-[220px]',
    'until-639:[&_article_h3]:text-[length:20px]',
    '[.reference-site.reference-site_&_article]:block [.reference-site.reference-site_&_article]:flex-[1_0_280px] [.reference-site.reference-site_&_article]:min-w-0',
    '[.reference-site.reference-site_&_article:not(:first-child)]:block [.reference-site.reference-site_&_article:not(:first-child)]:flex-[1_0_280px] [.reference-site.reference-site_&_article:not(:first-child)]:min-w-0',
    '[.reference-site.reference-site_&_article_>_div:first-child]:h-[210px] [.reference-site.reference-site_&_article_>_div:first-child]:aspect-[auto]',
    '[.reference-site.reference-site_&_article:not(:first-child)_>_div:first-child]:h-[210px] [.reference-site.reference-site_&_article:not(:first-child)_>_div:first-child]:aspect-[auto]',
    '[.reference-site.reference-site_&_article:first-child_h3]:text-[length:18px]',
  ].join(' '),
  'chapter-discover': ['[background:var(--home-page)]'].join(' '),
  'chapter-eyebrow': [
    'block text-home-accent text-[length:11px] font-extrabold tracking-[0.17em] uppercase mb-3.5',
  ].join(' '),
  'chapter-heading': [
    'flex items-end justify-between gap-6 mb-12',
    '[&_h2]:font-extrabold [&_h2]:m-[0_0_14px]',
    '[&_p]:text-home-secondary [&_p]:max-w-[530px] [&_p]:leading-[1.7]',
    'until-639:block',
    '[.featured-chapter_&_h2]:text-home-text',
  ].join(' '),
  'chapter-locations': ['[background:var(--home-page)]'].join(' '),
  'chapter-merchandise': [
    '[background:radial-gradient(ellipse_at_85%_30%,_#169bc90c,_transparent_55%),_var(--home-page)]',
    '[.reference-site.reference-site_&_img]:transform-none',
  ].join(' '),
  'chapter-organizers': [
    '![background:radial-gradient(ellipse_at_80%_60%,_#0ba2d91d,_transparent_50%),_#0a1622] [--home-accent:#72d0ff] [--home-accent-soft:#17334a]',
  ].join(' '),
  'chapter-partners': [
    '![background:var(--home-elevated)] [border-block:1px_solid_var(--home-line)]',
  ].join(' '),
  'chapter-resale': [
    '![background:linear-gradient(135deg,_#101e2c,_#101820)] [--home-accent:#72d0ff] [--home-accent-soft:#17334a]',
    '[&_article]:w-[auto] [&_article]:shadow-none [&_article]:[border:1px_solid_var(--home-line)]',
    'from-960:[&_article]:grid from-960:[&_article]:grid-cols-[38%_minmax(0,_1fr)]',
    'from-960:[&_article_>_div:first-child]:aspect-[auto] from-960:[&_article_>_div:first-child]:h-full',
    'from-960:[&_article_>_div:first-child_>_img]:absolute',
    '[.reference-site.reference-site_&_article]:flex [.reference-site.reference-site_&_article]:flex-col [.reference-site.reference-site_&_article]:flex-[1_0_calc((100%_-_60px)_/_4)] [.reference-site.reference-site_&_article]:min-w-[270px] [.reference-site.reference-site_&_article]:w-[auto]',
    '[.reference-site.reference-site_&_article_>_div:first-child]:h-[190px] [.reference-site.reference-site_&_article_>_div:first-child]:aspect-[auto] [.reference-site.reference-site_&_article_>_div:first-child]:flex-[none]',
    '[.reference-site.reference-site_&_article_>_div:first-child_>_img]:absolute',
    'until-1099:[.reference-site.reference-site_&_article]:flex-[0_0_300px]',
    'until-639:[.reference-site.reference-site_&_article]:basis-[min(290px,_85vw)] until-639:[.reference-site.reference-site_&_article]:min-w-0',
  ].join(' '),
  'chapter-stars': [
    '[background:var(--home-page)]',
    '[.reference-site.reference-site_&.chapter-stars]:py-10',
    'until-639:[.reference-site.reference-site_&.chapter-stars]:py-7',
  ].join(' '),
  container: [
    'legacy:w-[min(var(--content-width),_calc(100%_-_64px))] legacy:[margin-inline:auto]',
    'legacy:until-760:w-[calc(100%_-_36px)]',
    'legacy:until-370:w-[calc(100%_-_28px)]',
  ].join(' '),
  'content-page': ['legacy:[padding-block:40px_65px] legacy:min-h-[55vh]'].join(' '),
  'create-link': ['legacy:until-1150:hidden'].join(' '),
  'demo-label': [
    'legacy:p-[6px_10px] legacy:[border:1px_solid_var(--line)] legacy:rounded-[6px] legacy:text-muted legacy:text-[length:10px] legacy:whitespace-nowrap',
    'legacy:until-760:text-[length:8px]',
  ].join(' '),
  'detail-copy': [
    'legacy:[&_h1]:text-[length:35px] legacy:[&_h1]:leading-[1.2] legacy:[&_h1]:m-[15px_0]',
    'legacy:[&_p]:text-muted legacy:[&_p]:text-[length:14px]',
    'legacy:until-760:[&_h1]:text-[length:30px]',
  ].join(' '),
  'detail-grid': [
    'legacy:grid legacy:grid-cols-[1.4fr_1fr] legacy:gap-[35px]',
    'legacy:until-760:grid-cols-[1fr]',
  ].join(' '),
  'detail-info': [
    'legacy:[background:var(--surface)] legacy:p-[22px] legacy:[border:1px_solid_var(--line)] legacy:rounded-[var(--radius-md)]',
    'legacy:[&_dl]:m-[0]',
    'legacy:[&_dt]:text-muted legacy:[&_dt]:text-[length:11px] legacy:[&_dt]:mt-4',
    'legacy:[&_dd]:text-[length:14px] legacy:[&_dd]:m-[5px_0]',
  ].join(' '),
  'discovery-section': ['legacy:mt-[52px]', 'legacy:[.export-home_&]:mt-[0]'].join(' '),
  'editorial-hero': [
    'relative isolate text-[color:#f7f8fa] [background:#091320] p-[72px_0_0]',
    'until-639:pt-11',
  ].join(' '),
  'empty-state': [
    'legacy:text-center legacy:p-[65px_20px] legacy:[border:1px_dashed_var(--line)] legacy:rounded-[var(--radius-md)]',
    'legacy:[&_p]:text-muted legacy:[&_p]:text-[length:14px]',
  ].join(' '),
  'event-art': [
    'legacy:relative legacy:flex legacy:flex-col legacy:justify-between legacy:aspect-[1.7] legacy:p-[23px] legacy:isolate legacy:overflow-hidden legacy:text-[color:#f1fcff]',
    'legacy:[&_>_strong]:relative legacy:[&_>_strong]:[white-space:pre-line] legacy:[&_>_strong]:text-[length:clamp(27px,_2.9vw,_40px)] legacy:[&_>_strong]:[font-weight:750] legacy:[&_>_strong]:leading-[1.02] legacy:[&_>_strong]:tracking-[-0.055em]',
    'legacy:[.detail-grid_&]:rounded-[var(--radius-md)]',
    'legacy:until-760:p-[15px] legacy:until-760:aspect-[1.2]',
    'legacy:until-760:[&_>_strong]:text-[length:clamp(23px,_5vw,_34px)]',
    'legacy:until-370:aspect-[1.7]',
    'legacy:[.export-home_&]:aspect-[4_/_3]',
    'legacy:[.featured-grid_&_>_strong]:text-[length:31px]',
    'legacy:[.reopening-card_&]:aspect-[auto] legacy:[.reopening-card_&]:min-h-[230px] legacy:[.reopening-card_&]:p-[15px]',
    'legacy:[.reopening-card_&_>_strong]:text-[length:30px]',
    'legacy:until-760:[.featured-grid_&_>_strong]:text-[length:24px]',
    'legacy:until-760:[.reopening-card_&]:aspect-[16_/_9] legacy:until-760:[.reopening-card_&]:min-h-[190px]',
  ].join(' '),
  'event-card': [
    'legacy:[border:1px_solid_var(--line)] legacy:rounded-[var(--radius-md)] legacy:[background:var(--surface)] legacy:overflow-hidden legacy:[transition:box-shadow_0.2s,_transform_0.2s]',
    'legacy:[&:hover]:shadow-[var(--shadow)] legacy:[&:hover]:[transform:translateY(-4px)]',
    'legacy:[&_h3]:m-[9px_0_12px] legacy:[&_h3]:text-[length:17px] legacy:[&_h3]:min-h-[45px] legacy:[&_h3]:leading-[1.4]',
    'legacy:[&_p]:flex legacy:[&_p]:items-center legacy:[&_p]:flex-wrap legacy:[&_p]:gap-1.5 legacy:[&_p]:text-[length:11px] legacy:[&_p]:text-muted',
    'legacy:until-1150:[&_p]:text-[length:10px]',
    'legacy:until-760:[&_h3]:text-[length:14px] legacy:until-760:[&_h3]:min-h-[58px]',
    'legacy:until-760:[&_p]:gap-1',
    'legacy:[.export-home_&_h3]:text-[length:16px]',
    'legacy:until-760:[.export-home_&_h3]:text-[length:14px]',
  ].join(' '),
  'event-card-': [
    'legacy:[&:scope]:p-[19px_20px_14px]',
    'legacy:until-760:[&:scope]:p-[14px_12px]',
  ].join(' '),
  'event-card-body': ['legacy:until-760:[.export-home_&]:p-[13px]'].join(' '),
  'event-card-link': ['legacy:block legacy:h-full'].join(' '),
  'event-grid': [
    'legacy:grid legacy:grid-cols-[repeat(3,_1fr)] legacy:gap-[25px]',
    'legacy:until-760:grid-cols-[repeat(2,_1fr)] legacy:until-760:gap-3.5',
    'legacy:until-370:grid-cols-[1fr]',
    'legacy:[.export-home_&]:grid-cols-[repeat(3,_1fr)]',
    'legacy:until-760:[.export-home_&]:grid-cols-[repeat(2,_1fr)] legacy:until-760:[.export-home_&]:gap-3.5',
    'legacy:until-370:[.export-home_&]:grid-cols-[1fr]',
  ].join(' '),
  'event-organizer': [
    'legacy:flex legacy:justify-between legacy:items-center legacy:gap-2 legacy:m-[12px_0] legacy:text-[length:9px] legacy:text-muted',
    'legacy:until-760:flex-wrap',
  ].join(' '),
  'event-photo': [
    'legacy:absolute legacy:inset-[0] legacy:w-full legacy:h-full legacy:object-cover legacy:z-[-1]',
  ].join(' '),
  'event-venue': ['legacy:min-h-6'].join(' '),
  'explore-search': [
    'legacy:flex legacy:items-center legacy:gap-3 legacy:p-[7px_8px_7px_15px] legacy:[border:1px_solid_var(--line)] legacy:rounded-[12px] legacy:[background:var(--surface)] legacy:mb-[18px] legacy:text-muted',
    'legacy:[&_input]:w-full legacy:[&_input]:min-w-0 legacy:[&_input]:border-0 legacy:[&_input]:[background:transparent] legacy:[&_input]:text-foreground legacy:[&_input]:text-[length:14px] legacy:[&_input]:min-h-[35px]',
    'legacy:[&_input::placeholder]:text-muted',
  ].join(' '),
  eyebrow: [
    'legacy:inline-flex legacy:items-center legacy:gap-[9px] legacy:text-accent legacy:text-[length:10px] legacy:leading-[1.6] legacy:[font-weight:750] legacy:tracking-[0.13em]',
  ].join(' '),
  'favorite-button': [
    'absolute top-3 right-3 w-11 h-11 grid place-items-center [background:#0a1422e6] text-[color:#fff] [border:1px_solid_#ffffff40] rounded-full',
    "[&[aria-pressed='true']]:text-[color:#75d4ff]",
  ].join(' '),
  'featured-chapter': [
    'relative [background:radial-gradient(ellipse_at_80%_15%,_#159bd61a,_transparent_48%),_radial-gradient(ellipse_at_10%_90%,_#5380ad12,_transparent_40%),_var(--home-elevated)] [border-block:1px_solid_var(--home-line)]',
    "[&::before]:[content:''] [&::before]:pointer-events-none [&::before]:absolute [&::before]:inset-[0] [&::before]:opacity-[0.22] [&::before]:[background-image:radial-gradient(var(--home-muted)_0.6px,_transparent_0.6px)] [&::before]:[background-size:24px_24px] [&::before]:[mask-image:linear-gradient(to_bottom,_#000,_transparent_65%)]",
  ].join(' '),
  'featured-hover-rail': [
    'flex gap-5 items-stretch p-[10px_4px_18px]',
    'until-1099:overflow-x-auto until-1099:[scroll-snap-type:x_mandatory]',
  ].join(' '),
  'filter-bar': [
    'legacy:[border-top:1px_solid_var(--line)] legacy:[border-bottom:1px_solid_var(--line)] legacy:p-[14px_0]',
    'legacy:from-1350:flex legacy:from-1350:justify-between legacy:from-1350:items-center legacy:from-1350:gap-3',
    'legacy:[.export-home_&]:block',
  ].join(' '),
  'filter-selects': [
    'legacy:flex legacy:[justify-content:end] legacy:gap-3.5 legacy:mt-3',
    'legacy:[&_label]:flex legacy:[&_label]:items-center legacy:[&_label]:gap-1.5 legacy:[&_label]:text-muted legacy:[&_label]:text-[length:12px]',
    'legacy:[&_select]:[background:var(--surface)] legacy:[&_select]:[border:1px_solid_var(--line)] legacy:[&_select]:rounded-[7px] legacy:[&_select]:p-2',
    'legacy:from-1350:mt-[0]',
    'legacy:[&_input]:[border:1px_solid_var(--line)] legacy:[&_input]:[background:var(--surface)] legacy:[&_input]:rounded-[7px] legacy:[&_input]:p-[7px] legacy:[&_input]:text-[length:12px]',
    'legacy:[.export-home_&]:mt-3.5',
    'legacy:until-760:flex-wrap legacy:until-760:[justify-content:start]',
  ].join(' '),
  'filter-tabs': [
    'legacy:flex legacy:gap-2 legacy:overflow-x-auto legacy:p-[3px]',
    'legacy:[&_button]:p-[9px_13px] legacy:[&_button]:[border:1px_solid_transparent] legacy:[&_button]:rounded-[8px] legacy:[&_button]:whitespace-nowrap legacy:[&_button]:text-[length:12px] legacy:[&_button]:text-muted',
    'legacy:[&_button:hover]:text-accent',
    'legacy:from-1350:gap-0.5',
    'legacy:from-1350:[&_button]:px-2.5',
  ].join(' '),
  'font-extrabold': ['[.reference-site.reference-site_article_.text-lg&]:whitespace-nowrap'].join(
    ' ',
  ),
  'footer-bottom': [
    'legacy:flex legacy:justify-between legacy:gap-[15px] legacy:[border-top:1px_solid_var(--line)] legacy:py-5 legacy:text-[length:10px] legacy:text-muted',
    'legacy:until-760:flex-col legacy:until-760:gap-2',
  ].join(' '),
  'footer-note': ['legacy:until-760:[align-self:start]'].join(' '),
  'footer-top': [
    'legacy:grid legacy:grid-cols-[1.4fr_1fr_1fr_1.1fr] legacy:gap-[35px] legacy:pb-[35px]',
    'legacy:[&_h2]:text-[length:12px] legacy:[&_h2]:mb-5 legacy:[&_h2]:tracking-[0]',
    'legacy:[&_p]:text-[length:12px] legacy:[&_p]:text-muted legacy:[&_p]:mt-[15px]',
    'legacy:[&_>_div_>_a:not(.brand)]:block legacy:[&_>_div_>_a:not(.brand)]:text-[length:12px] legacy:[&_>_div_>_a:not(.brand)]:text-muted legacy:[&_>_div_>_a:not(.brand)]:mb-3',
    'legacy:until-760:grid-cols-[1fr_1fr] legacy:until-760:gap-[25px]',
  ].join(' '),
  grid: [
    '[.chapter-locations_&]:grid-cols-[1.5fr_1fr_1fr]',
    '[.chapter-locations_&_>_button]:h-[180px]',
    '[.chapter-locations_&_>_button:first-child]:row-[span_2] [.chapter-locations_&_>_button:first-child]:h-full [.chapter-locations_&_>_button:first-child]:min-h-[376px]',
    '[.chapter-locations_&_>_button:first-child_h3]:text-[length:30px]',
    '[.chapter-blog_&]:grid-cols-[1.35fr_1fr]',
    'until-959:[.chapter-blog_&]:grid-cols-[1fr_1fr]',
    'until-639:[.chapter-locations_&]:grid-cols-[minmax(0,_1fr)]',
    'until-639:[.chapter-blog_&]:grid-cols-[minmax(0,_1fr)]',
    'until-639:[.chapter-locations_&_>_button]:h-[220px] until-639:[.chapter-locations_&_>_button]:min-h-[0] until-639:[.chapter-locations_&_>_button]:row-[auto]',
    'until-639:[.chapter-locations_&_>_button:first-child]:h-[220px] until-639:[.chapter-locations_&_>_button:first-child]:min-h-[0] until-639:[.chapter-locations_&_>_button:first-child]:row-[auto]',
    '[.reference-site.reference-site_.chapter-locations_&]:flex [.reference-site.reference-site_.chapter-locations_&]:gap-4 [.reference-site.reference-site_.chapter-locations_&]:overflow-x-auto [.reference-site.reference-site_.chapter-locations_&]:p-[5px_2px_14px] [.reference-site.reference-site_.chapter-locations_&]:[scroll-snap-type:x_mandatory]',
    '[.reference-site.reference-site_.chapter-locations_&_>_button]:flex-[1_0_180px] [.reference-site.reference-site_.chapter-locations_&_>_button]:h-[200px] [.reference-site.reference-site_.chapter-locations_&_>_button]:min-h-[0] [.reference-site.reference-site_.chapter-locations_&_>_button]:row-[auto] [.reference-site.reference-site_.chapter-locations_&_>_button]:[scroll-snap-align:start]',
    '[.reference-site.reference-site_.chapter-locations_&_>_button:first-child]:flex-[1_0_180px] [.reference-site.reference-site_.chapter-locations_&_>_button:first-child]:h-[200px] [.reference-site.reference-site_.chapter-locations_&_>_button:first-child]:min-h-[0] [.reference-site.reference-site_.chapter-locations_&_>_button:first-child]:row-[auto] [.reference-site.reference-site_.chapter-locations_&_>_button:first-child]:[scroll-snap-align:start]',
    '[.reference-site.reference-site_.chapter-locations_&_>_button:first-child_h3]:text-[length:18px]',
    '[.reference-site.reference-site_.chapter-blog_&]:flex [.reference-site.reference-site_.chapter-blog_&]:gap-5 [.reference-site.reference-site_.chapter-blog_&]:overflow-x-auto [.reference-site.reference-site_.chapter-blog_&]:pb-3',
    'until-639:[.reference-site.reference-site_.chapter-locations_&_>_button]:basis-[180px] until-639:[.reference-site.reference-site_.chapter-locations_&_>_button]:h-[180px]',
    'until-639:[.reference-site.reference-site_.chapter-locations_&_>_button:first-child]:basis-[180px] until-639:[.reference-site.reference-site_.chapter-locations_&_>_button:first-child]:h-[180px]',
  ].join(' '),
  'grid-cols-2': ['until-639:[.chapter-merchandise_&]:grid-cols-[minmax(0,_1fr)]'].join(' '),
  group: ['[.reference-site_&:hover_img]:transform-none'].join(' '),
  'has-photo': [
    "legacy:[.event-art&::after]:[content:''] legacy:[.event-art&::after]:absolute legacy:[.event-art&::after]:inset-[0] legacy:[.event-art&::after]:z-[-1] legacy:[.event-art&::after]:[background:linear-gradient(180deg,_#061c3470,_#061c3490)]",
    'legacy:[.event-art&]:text-[color:#f4faff]',
  ].join(' '),
  'header-actions': [
    'legacy:flex legacy:items-center legacy:gap-[18px] legacy:text-[length:12px] legacy:font-semibold',
    'legacy:until-1150:gap-3',
    'legacy:until-760:ml-[auto]',
  ].join(' '),
  'header-main': [
    'legacy:flex legacy:items-center legacy:gap-[26px] legacy:min-h-[82px]',
    'legacy:until-1150:gap-[18px]',
    'legacy:until-760:min-h-[70px] legacy:until-760:gap-3 legacy:until-760:flex-wrap legacy:until-760:py-3',
  ].join(' '),
  'header-search': [
    'legacy:flex legacy:items-center legacy:gap-2.5 legacy:flex-[1] legacy:[background:var(--surface)] legacy:[border:1px_solid_var(--line)] legacy:rounded-[10px] legacy:p-[7px_12px] legacy:text-muted',
    'legacy:[&_input]:w-full legacy:[&_input]:border-0 legacy:[&_input]:[background:transparent] legacy:[&_input]:text-[length:12px] legacy:[&_input]:p-[7px_0]',
    'legacy:[&_input::placeholder]:text-muted',
    'legacy:[&_button]:grid legacy:[&_button]:place-items-center legacy:[&_button]:border-0 legacy:[&_button]:min-w-8 legacy:[&_button]:min-h-8 legacy:[&_button]:text-accent',
    'legacy:until-760:[order:4] legacy:until-760:basis-[100%]',
  ].join(' '),
  'header-site-links': [
    'legacy:flex legacy:items-center legacy:gap-4 legacy:text-[length:12px] legacy:font-semibold legacy:whitespace-nowrap',
    'legacy:until-1250:hidden',
  ].join(' '),
  'hero-actions': [
    'flex gap-6 items-center flex-wrap m-[32px_0_26px]',
    'until-639:gap-4',
    'legacy:flex legacy:items-center legacy:gap-[22px]',
    'legacy:until-760:[.home-organizer_&]:flex-wrap',
  ].join(' '),
  'hero-backdrop': [
    'absolute inset-[0] z-[-1] [background:radial-gradient(ellipse_at_20%_15%,_#0873a431,_transparent_48%),_radial-gradient(ellipse_at_85%_60%,_#567ba31c,_transparent_50%),_linear-gradient(130deg,_#0c1d2b,_#080b11)]',
  ].join(' '),
  'hero-copy': [
    '[&_h1]:text-[length:clamp(42px,_4.8vw,_70px)] [&_h1]:leading-[1.06] [&_h1]:tracking-[-0.055em] [&_h1]:font-extrabold [&_h1]:m-[0_0_24px]',
    '[&_h1_em]:not-italic [&_h1_em]:text-[color:#70d0ff]',
    '[&_>_p]:max-w-[430px] [&_>_p]:text-[length:16px] [&_>_p]:leading-[1.85] [&_>_p]:text-[color:#b8c6d7]',
    'until-959:[&_h1]:text-[length:44px]',
    'until-639:[&_h1]:text-[length:clamp(38px,_9.7vw,_58px)]',
    'until-639:[&_>_p]:text-[length:15px]',
  ].join(' '),
  'hero-discovery-strip': [
    'flex items-center flex-wrap gap-7 py-[22px] [border-top:1px_solid_#ffffff19] text-[color:#d4deeb] text-[length:13px]',
    '[&_>_a]:flex [&_>_a]:items-center [&_>_a]:gap-2.5 [&_>_a]:min-h-11',
    '[&_>_span]:flex [&_>_span]:items-center [&_>_span]:gap-2.5 [&_>_span]:min-h-11 [&_>_span]:text-[color:#a4b6ca] [&_>_span]:mr-[auto]',
    '[&_a:hover]:text-[color:#70d0ff]',
    'until-639:gap-[4px_22px] until-639:py-4',
    'until-639:[&_>_span]:basis-[100%]',
    'until-639:[&_a]:text-[length:12px]',
  ].join(' '),
  'hero-editorial-grid': [
    'grid grid-cols-[1.05fr_1fr] items-center gap-16 pb-[72px]',
    'until-1199:gap-9',
    'until-959:gap-7 until-959:grid-cols-[1fr_1fr]',
    'until-639:grid-cols-[1fr] until-639:pb-8 until-639:gap-9',
  ].join(' '),
  'hero-event-preview': [
    'block relative min-h-[460px] [align-self:stretch] rounded-[24px] overflow-hidden [border:1px_solid_#ffffff26] shadow-[0_30px_90px_#0005]',
    '[&_>_img]:absolute [&_>_img]:w-full [&_>_img]:h-full [&_>_img]:object-cover',
    "[&::after]:[content:''] [&::after]:absolute [&::after]:inset-[0] [&::after]:[background:linear-gradient(180deg,_#06101c33_10%,_transparent_30%,_#06101cf2_100%)]",
    'until-959:min-h-[420px]',
    'until-639:min-h-[330px]',
  ].join(' '),
  'hero-kicker': [
    'flex gap-2.5 items-center text-[color:#a5d9f1] text-[length:12px] [font-weight:650] tracking-[0.02em] mb-7',
    '[&_>_span]:w-1.5 [&_>_span]:h-1.5 [&_>_span]:[background:#65cfff] [&_>_span]:rounded-full [&_>_span]:shadow-[0_0_0_5px_#65cfff12]',
    'until-639:text-[length:11px]',
  ].join(' '),
  'hero-note': [
    'flex gap-2.5 items-center text-[color:#a8b7ca] text-[length:12px]',
    '[&_svg]:text-[color:#70d0ff]',
  ].join(' '),
  'hero-preview-bottom': [
    'absolute z-[1] left-7 right-7 bottom-7',
    '[&_h2]:text-[length:clamp(24px,_2.2vw,_34px)] [&_h2]:leading-[1.2] [&_h2]:tracking-[-0.035em] [&_h2]:font-extrabold [&_h2]:m-[12px_0_18px] [&_h2]:max-w-[400px]',
    '[&_p]:flex [&_p]:items-center [&_p]:flex-wrap [&_p]:gap-2 [&_p]:text-[color:#d4deeb] [&_p]:text-[length:12px]',
    'until-959:left-5 until-959:right-5',
    'until-639:[&_h2]:text-[length:26px]',
  ].join(' '),
  'hero-preview-category': ['text-[color:#9cddff] text-[length:12px] [font-weight:650]'].join(' '),
  'hero-preview-top': [
    'absolute z-[1] left-7 right-7 top-6 flex justify-between items-center',
    '[&_>_span]:p-[8px_12px] [&_>_span]:[border:1px_solid_#ffffff3b] [&_>_span]:[background:#06101ccc] [&_>_span]:rounded-[100px] [&_>_span]:text-[length:10px] [&_>_span]:font-extrabold [&_>_span]:tracking-[0.14em]',
    'until-959:left-5 until-959:right-5',
  ].join(' '),
  'hero-secondary': [
    'text-[color:#eef5fc] flex items-center gap-2.5 min-h-12 text-[length:14px] font-bold',
  ].join(' '),
  'home-brand': [
    'flex gap-3 items-center shrink-0',
    '[&_strong]:text-[length:22px] [&_strong]:tracking-[-1px]',
    '[&_small]:block [&_small]:text-[length:8px] [&_small]:font-extrabold [&_small]:tracking-[0.18em] [&_small]:uppercase [&_small]:text-home-accent [&_small]:mt-0.5',
    'until-639:[&_small]:hidden',
    'until-639:gap-[9px]',
    'until-639:[&_strong]:text-[length:20px]',
  ].join(' '),
  'home-button': [
    '[.reference-site.reference-site_&]:min-h-11',
    '[.reference-site.reference-site_.bg-primary-600&]:[background:var(--home-button)] [.reference-site.reference-site_.bg-primary-600&]:text-home-button-text',
  ].join(' '),
  'home-chapter': [
    '[.reference-site.reference-site_&]:py-[60px]',
    '[&_h2]:text-[length:clamp(28px,_3.1vw,_42px)] [&_h2]:leading-[1.17] [&_h2]:tracking-[-0.045em]',
    '[&_>_div_>_div:first-child:has(h2)]:mb-7',
    'until-959:[.reference-site.reference-site_&]:py-[76px]',
    'until-639:[.reference-site.reference-site_&]:py-10',
    'until-639:[&_>_div_>_div:first-child:has(h2)]:mb-6',
    'until-639:[&_h2]:text-[length:30px]',
  ].join(' '),
  'home-container': [
    'w-[min(1280px,_calc(100%_-_80px))] mx-auto',
    '[.featured-chapter_>_&]:relative',
    'until-959:w-[calc(100%_-_48px)]',
    'until-639:w-[calc(100%_-_40px)]',
  ].join(' '),
  'home-cta': [
    'inline-flex items-center justify-center gap-3 min-h-12 p-[12px_20px] rounded-[12px] [background:var(--home-button)] text-home-button-text text-[length:14px] font-extrabold whitespace-nowrap [transition:background_200ms_ease,_transform_200ms_ease,_box-shadow_200ms_ease]',
    '[&:hover]:[transform:translateY(-2px)] [&:hover]:shadow-[0_6px_22px_#008fc629]',
    '[&:hover_svg]:[transform:translateX(3px)]',
    '[.hero-actions_&]:[--home-button:#55c5ff] [.hero-actions_&]:[--home-button-text:#071926] [.hero-actions_&]:min-h-[52px] [.hero-actions_&]:px-6',
    '[.spotlight-bottom_&]:min-h-11 [.spotlight-bottom_&]:p-[10px_13px] [.spotlight-bottom_&]:text-[length:12px]',
    'until-639:[.hero-actions_&]:px-[18px]',
    '[.featured-hover-rail_.spotlight-bottom_&]:w-full',
  ].join(' '),
  'home-link': [
    'inline-flex items-center gap-3 text-[length:14px] font-bold min-h-11 text-home-accent whitespace-nowrap',
    '[&:hover_svg]:[transform:translateX(3px)]',
    'until-639:[.chapter-heading_>_&]:mt-4',
  ].join(' '),
  'home-mobile-menu': [
    'overflow-hidden origin-top p-[16px_24px_24px] [background:var(--home-nav)] [border-top:1px_solid_var(--home-line)] [transition:max-height_420ms_cubic-bezier(0.22,_1,_0.36,_1),_opacity_240ms_ease,_transform_420ms_cubic-bezier(0.22,_1,_0.36,_1),_visibility_0s_linear_420ms] from-960:hidden',
    '[&_a]:flex [&_a]:items-center [&_a]:min-h-12 [&_a]:text-home-text',
  ].join(' '),
  'home-nav': [
    'max-w-[1440px] m-[auto] p-[0_32px] min-h-20 flex items-center gap-[26px]',
    'until-1199:gap-5 until-1199:px-6',
    'until-639:min-h-[72px] until-639:px-5 until-639:gap-3',
  ].join(' '),
  'home-nav-actions': [
    'flex items-center gap-3 ml-[auto]',
    'until-959:ml-[auto]',
    'until-639:gap-[0]',
  ].join(' '),
  'home-nav-links': [
    'flex items-center gap-5 ml-[auto]',
    '[&_a]:text-[length:13px] [&_a]:[font-weight:650] [&_a]:text-home-secondary [&_a]:py-3.5 [&_a]:whitespace-nowrap',
    "[&_a]:relative [&_a]:[transition:color_220ms_ease] [&_a::after]:[content:''] [&_a::after]:absolute [&_a::after]:left-0 [&_a::after]:right-0 [&_a::after]:bottom-1.5 [&_a::after]:h-0.5 [&_a::after]:rounded-full [&_a::after]:bg-home-accent [&_a::after]:scale-x-0 [&_a::after]:origin-left [&_a::after]:[transition:scale_360ms_cubic-bezier(0.22,_1,_0.36,_1)]",
    '[&_a:hover]:text-home-accent [&_a:hover::after]:scale-x-50 [&_a[aria-current=location]]:text-home-accent [&_a[aria-current=location]::after]:scale-x-100',
    'until-1199:gap-4',
    'until-959:hidden',
  ].join(' '),
  'home-navbar': [
    'sticky top-[0] z-[60] [border-bottom:1px_solid_var(--home-line)] [background:var(--home-nav)] text-home-text will-change-transform [transition:transform_620ms_cubic-bezier(0.22,_1,_0.36,_1),_opacity_420ms_ease,_box-shadow_420ms_ease]',
    '[&:focus-within]:[transform:translateY(0)] [&:focus-within]:opacity-100 [&:focus-within]:pointer-events-auto',
  ].join(' '),
  icon: [
    'legacy:w-5 legacy:h-5 legacy:shrink-0 legacy:[vertical-align:middle]',
    'legacy:[.event-card_p_&]:w-3.5 legacy:[.event-card_p_&]:h-3.5',
    'legacy:[.empty-state_>_&]:w-[35px] legacy:[.empty-state_>_&]:h-[35px] legacy:[.empty-state_>_&]:text-accent legacy:[.empty-state_>_&]:mb-[15px]',
    'legacy:[.journal-card_>_&]:ml-[auto] legacy:[.journal-card_>_&]:text-accent',
    'legacy:until-760:[.card-arrow_&]:w-4',
    'legacy:[.partner-empty_>_&]:w-[37px] legacy:[.partner-empty_>_&]:h-[37px] legacy:[.partner-empty_>_&]:text-accent',
    'legacy:[.blog-cover_>_&]:w-[75px] legacy:[.blog-cover_>_&]:h-[75px] legacy:[.blog-cover_>_&]:[transform:rotate(-18deg)] legacy:[.blog-cover_>_&]:opacity-[0.65]',
    'legacy:[.organizer-steps_&]:text-accent legacy:[.organizer-steps_&]:w-[27px] legacy:[.organizer-steps_&]:h-[27px] legacy:[.organizer-steps_&]:mb-[17px]',
    'legacy:until-760:[.blog-cover_>_&]:w-[45px] legacy:until-760:[.blog-cover_>_&]:h-[45px]',
  ].join(' '),
  'icon-button': [
    'legacy:inline-grid legacy:place-items-center legacy:[border:1px_solid_var(--line)] legacy:rounded-[9px] legacy:w-11 legacy:h-11',
  ].join(' '),
  'is-open': [
    'legacy:until-760:[.category-nav&]:block',
    'legacy:until-760:[.home-header_.category-nav&]:block',
  ].join(' '),
  'journal-card': [
    'legacy:flex legacy:items-center legacy:gap-[22px] legacy:p-[27px] legacy:[border:1px_solid_var(--line)] legacy:rounded-[var(--radius-md)] legacy:[background:var(--surface)]',
    'legacy:[&_h3]:text-[length:18px] legacy:[&_h3]:leading-[1.5] legacy:[&_h3]:m-[9px_0_0]',
    'legacy:until-1150:p-5 legacy:until-1150:gap-[15px]',
    'legacy:until-1150:[&_h3]:text-[length:16px]',
  ].join(' '),
  'journal-number': [
    'legacy:text-accent legacy:text-[length:42px] legacy:[font-weight:300]',
    'legacy:until-1150:text-[length:33px]',
  ].join(' '),
  'legacy-site': [
    "legacy:[&:scope]:[font-family:'Segoe_UI',_system-ui,_sans-serif] legacy:[&:scope]:text-foreground legacy:[&:scope]:[background:var(--page)] legacy:[&:scope]:[font-synthesis:none] legacy:[&:scope]:[text-rendering:optimizeLegibility] legacy:[&:scope]:[-webkit-font-smoothing:antialiased] legacy:[&:scope]:scroll-smooth legacy:[&:scope]:[scroll-padding-top:155px] legacy:[&:scope]:m-[0] legacy:[&:scope]:min-w-80",
    'legacy:[:where(&:scope)_*]:box-border',
    'legacy:[:where(&:scope)_a]:text-[color:inherit] legacy:[:where(&:scope)_a]:no-underline legacy:[:where(&:scope)_a]:[-webkit-tap-highlight-color:transparent]',
    'legacy:[:where(&:scope)_button]:[font:inherit] legacy:[:where(&:scope)_button]:text-[color:inherit] legacy:[:where(&:scope)_button]:cursor-pointer legacy:[:where(&:scope)_button]:[background:none] legacy:[:where(&:scope)_button]:[-webkit-tap-highlight-color:transparent]',
    'legacy:[:where(&:scope)_input]:[font:inherit] legacy:[:where(&:scope)_input]:text-[color:inherit] legacy:[:where(&:scope)_input]:min-w-0 legacy:[:where(&:scope)_input]:[-webkit-tap-highlight-color:transparent]',
    'legacy:[:where(&:scope)_select]:[font:inherit] legacy:[:where(&:scope)_select]:text-[color:inherit] legacy:[:where(&:scope)_select]:cursor-pointer legacy:[:where(&:scope)_select]:min-w-0 legacy:[:where(&:scope)_select]:[-webkit-tap-highlight-color:transparent]',
    'legacy:[:where(&:scope)_button:disabled]:cursor-not-allowed legacy:[:where(&:scope)_button:disabled]:opacity-[0.65]',
    'legacy:[:where(&:scope)_:focus-visible]:[outline:3px_solid_var(--focus)] legacy:[:where(&:scope)_:focus-visible]:outline-offset-[4px]',
    'legacy:[:where(&:scope)_h1]:mt-[0] legacy:[:where(&:scope)_h1]:tracking-[-0.035em]',
    'legacy:[:where(&:scope)_h2]:mt-[0] legacy:[:where(&:scope)_h2]:tracking-[-0.035em]',
    'legacy:[:where(&:scope)_h3]:mt-[0] legacy:[:where(&:scope)_h3]:tracking-[-0.035em]',
    'legacy:[:where(&:scope)_p]:mt-[0] legacy:[:where(&:scope)_p]:leading-[1.7]',
    'legacy:[:where(&:scope)_select_option]:[background:var(--surface)] legacy:[:where(&:scope)_select_option]:text-foreground',
    'legacy:reduce-motion:[&:scope]:scroll-auto',
    'legacy:reduce-motion:[:where(&:scope)_*]:![transition:none] legacy:reduce-motion:[:where(&:scope)_*]:!animate-none',
    'legacy:reduce-motion:[:where(&:scope)_*::before]:![transition:none] legacy:reduce-motion:[:where(&:scope)_*::before]:!animate-none',
    'legacy:reduce-motion:[:where(&:scope)_*::after]:![transition:none] legacy:reduce-motion:[:where(&:scope)_*::after]:!animate-none',
  ].join(' '),
  'lg:flex-shrink-0': [
    '[.chapter-organizers_&]:max-w-[480px] [.chapter-organizers_&]:grid-cols-[1fr_1fr]',
    '[.chapter-organizers_&_>_div]:w-[auto] [.chapter-organizers_&_>_div]:min-w-0',
    '[.chapter-organizers_&_>_div:first-child]:col-[span_2]',
    'until-639:[.chapter-organizers_&]:max-w-[100%] until-639:[.chapter-organizers_&]:grid-cols-[1fr]',
    'until-639:[.chapter-organizers_&_>_div:first-child]:col-[auto]',
  ].join(' '),
  'merch-art': [
    'legacy:relative legacy:min-h-[345px] legacy:grid legacy:place-items-center legacy:[background:radial-gradient(ellipse_at_center,_var(--accent-soft),_var(--surface-raised))] legacy:overflow-hidden',
    'legacy:[.product-card_&]:min-h-[260px] legacy:[.product-card_&]:rounded-[12px]',
    'legacy:until-760:min-h-[310px]',
  ].join(' '),
  'mobile-menu-button': [
    'legacy:hidden',
    'legacy:until-760:inline-grid legacy:until-760:w-9 legacy:until-760:h-9',
  ].join(' '),
  'mobile-nav-actions': [
    'legacy:hidden',
    'legacy:until-760:flex legacy:until-760:gap-[30px] legacy:until-760:col-[1_/_-1] legacy:until-760:p-[15px_0] legacy:until-760:text-[length:13px] legacy:until-760:text-accent',
  ].join(' '),
  'nav-active': [
    'legacy:[.nav-inner_>_a&]:text-accent legacy:[.nav-inner_>_a&]:[border-bottom-color:var(--accent)]',
  ].join(' '),
  'nav-create': ['until-1199:hidden'].join(' '),
  'nav-divider': [
    'legacy:h-4 legacy:[border-left:1px_solid_var(--line)]',
    'legacy:until-760:hidden',
  ].join(' '),
  'nav-hidden': [
    '[.home-navbar&]:[transform:translateY(-110%)] [.home-navbar&]:opacity-0 [.home-navbar&]:pointer-events-none [.home-navbar&]:[transition-delay:100ms,_100ms,_0ms]',
  ].join(' '),
  'nav-visible': [
    '[.home-navbar&]:[transform:translateY(0)] [.home-navbar&]:opacity-100 [.home-navbar&]:shadow-[0_8px_28px_#0000000b] [.home-navbar&]:[transition-delay:140ms,_140ms,_140ms]',
  ].join(' '),
  'mobile-menu-open': [
    '[.home-mobile-menu&]:max-h-[460px] [.home-mobile-menu&]:opacity-100 [.home-mobile-menu&]:visible [.home-mobile-menu&]:translate-y-0 [.home-mobile-menu&]:[transition-delay:0s]',
  ].join(' '),
  'mobile-menu-closed': [
    '[.home-mobile-menu&]:max-h-0 [.home-mobile-menu&]:opacity-0 [.home-mobile-menu&]:invisible [.home-mobile-menu&]:pointer-events-none [.home-mobile-menu&]:-translate-y-2 [.home-mobile-menu&]:py-0',
  ].join(' '),
  'catalog-dock-visible': [
    '[.catalog-floating&]:opacity-100 [.catalog-floating&]:visible [.catalog-floating&]:translate-y-0 [.catalog-floating&]:pointer-events-auto [.catalog-floating&]:[transition-delay:0s]',
  ].join(' '),
  'catalog-dock-hidden': [
    '[.catalog-floating&]:opacity-0 [.catalog-floating&]:invisible [.catalog-floating&]:translate-y-[calc(100%_+_32px)] [.catalog-floating&]:scale-[0.98] [.catalog-floating&]:pointer-events-none',
  ].join(' '),
  'nav-inner': [
    'legacy:flex legacy:items-center legacy:justify-between legacy:gap-5 legacy:min-h-[52px]',
    'legacy:[&_>_a]:p-[16px_0] legacy:[&_>_a]:whitespace-nowrap legacy:[&_>_a]:text-[length:12px] legacy:[&_>_a]:font-semibold legacy:[&_>_a]:[border-bottom:2px_solid_transparent]',
    'legacy:[&_>_a:hover]:text-accent legacy:[&_>_a:hover]:[border-bottom-color:var(--accent)]',
    'legacy:until-1150:gap-[15px] legacy:until-1150:overflow-x-auto',
    'legacy:until-1150:[&_>_a]:text-[length:11px]',
    'legacy:until-760:grid legacy:until-760:grid-cols-[1fr_1fr] legacy:until-760:py-2.5 legacy:until-760:gap-[0_15px] legacy:until-760:max-h-[65vh] legacy:until-760:[overflow-y:auto]',
    'legacy:until-760:[&_>_a]:p-[12px_0] legacy:until-760:[&_>_a]:[white-space:normal] legacy:until-760:[&_>_a]:text-[length:12px]',
  ].join(' '),
  'nav-menu': [
    'hidden items-center justify-center w-11 [&_svg]:[transition:transform_320ms_cubic-bezier(0.22,_1,_0.36,_1),_opacity_180ms_ease]',
    "[&[aria-expanded='true']_svg]:rotate-90 [&:active_svg]:scale-90",
    'until-959:flex',
  ].join(' '),
  'nav-search': [
    'flex gap-2 items-center justify-center min-h-11 text-[length:13px] font-bold whitespace-nowrap w-11 [&_svg]:[transition:transform_280ms_ease] [&:hover_svg]:scale-110',
    'until-1199:hidden',
  ].join(' '),
  'nav-tickets': [
    'flex gap-2 items-center justify-center min-h-11 text-[length:13px] font-bold whitespace-nowrap',
    'until-959:hidden',
  ].join(' '),
  'no-scrollbar': [
    '[&::-webkit-scrollbar]:hidden',
    '[-ms-overflow-style:none] [scrollbar-width:none]',
  ].join(' '),
  notice: [
    'legacy:[border-left:3px_solid_var(--accent)] legacy:p-[14px_18px] legacy:[background:var(--accent-soft)] legacy:text-[length:13px] legacy:leading-[1.7] legacy:rounded-[0_8px_8px_0]',
  ].join(' '),
  'overflow-x-auto': [
    '[.chapter-stars_&_>_button]:![background:transparent] [.chapter-stars_&_>_button]:shadow-none [.chapter-stars_&_>_button]:[border-color:transparent] [.chapter-stars_&_>_button]:w-[180px] [.chapter-stars_&_>_button]:p-4',
    'until-639:[.chapter-stars_&_>_button]:w-40',
  ].join(' '),
  'p-5': [
    '[.chapter-resale_article_>_&]:[border-top:1px_dashed_var(--home-muted)]',
    '[.chapter-blog_article:not(:first-child)_&]:p-6',
    'from-960:[.chapter-resale_article_>_&]:[border-top:0] from-960:[.chapter-resale_article_>_&]:[border-left:1px_dashed_var(--home-muted)]',
    '[.reference-site.reference-site_.chapter-resale_article_>_&]:flex-[1] [.reference-site.reference-site_.chapter-resale_article_>_&]:[border-left:0] [.reference-site.reference-site_.chapter-resale_article_>_&]:[border-top:1px_dashed_var(--home-muted)] [.reference-site.reference-site_.chapter-resale_article_>_&]:p-[18px] [.reference-site.reference-site_.chapter-resale_article_>_&]:flex [.reference-site.reference-site_.chapter-resale_article_>_&]:flex-col',
    '[.reference-site.reference-site_.chapter-blog_article:not(:first-child)_&]:p-5',
  ].join(' '),
  'preview-status': [
    'legacy:[display:inline-block] legacy:p-[5px_7px] legacy:rounded-[20px] legacy:[background:var(--surface-raised)] legacy:text-muted legacy:whitespace-nowrap',
  ].join(' '),
  'price-label': ['block text-[length:11px] text-home-muted mb-[3px]'].join(' '),
  'product-art': [
    'legacy:grid legacy:place-items-center legacy:relative legacy:aspect-[1] legacy:overflow-hidden legacy:[background:var(--surface-raised)]',
  ].join(' '),
  'product-card': [
    'legacy:[background:var(--surface)] legacy:[border:1px_solid_var(--line)] legacy:rounded-[var(--radius-md)] legacy:p-[25px]',
    'legacy:[&_h3]:m-[18px_0_8px]',
    'legacy:[&_p]:text-[length:13px] legacy:[&_p]:text-muted',
    'legacy:[&_label]:flex legacy:[&_label]:flex-col legacy:[&_label]:gap-[7px] legacy:[&_label]:m-[15px_0] legacy:[&_label]:text-[length:13px]',
    'legacy:[&_select]:[border:1px_solid_var(--line)] legacy:[&_select]:[background:var(--surface)] legacy:[&_select]:rounded-[8px] legacy:[&_select]:p-2.5',
  ].join(' '),
  'product-grid': [
    'legacy:grid legacy:grid-cols-[1fr_1fr] legacy:gap-6 legacy:mt-[25px]',
    'legacy:until-760:grid-cols-[1fr]',
  ].join(' '),
  'product-motif': ['legacy:text-[length:45px]', 'legacy:until-760:text-[length:30px]'].join(' '),
  'product-object': [
    'legacy:relative legacy:flex legacy:flex-col legacy:items-center legacy:[justify-content:space-around] legacy:w-[55%] legacy:h-[62%] legacy:mt-[12%] legacy:p-3.5 legacy:[background:#e6e0d1] legacy:text-[color:#234655] legacy:[transform:rotate(-7deg)] legacy:shadow-[10px_18px_20px_#041b3520] legacy:rounded-[3px_3px_18px_18px]',
    'legacy:[&_>_span:first-child]:text-[length:19px] legacy:[&_>_span:first-child]:font-extrabold legacy:[&_>_span:first-child]:tracking-[-0.04em] legacy:[&_>_span:first-child]:text-center',
    'legacy:[&_small]:text-[length:7px] legacy:[&_small]:tracking-[0.13em]',
    "legacy:[.product-art-tote_&::before]:[content:''] legacy:[.product-art-tote_&::before]:absolute legacy:[.product-art-tote_&::before]:w-[50%] legacy:[.product-art-tote_&::before]:h-[35%] legacy:[.product-art-tote_&::before]:top-[-30%] legacy:[.product-art-tote_&::before]:[border:8px_solid_#dbd3bd] legacy:[.product-art-tote_&::before]:[border-bottom:none] legacy:[.product-art-tote_&::before]:rounded-[50%_50%_0_0]",
    'legacy:[.product-art-shirt_&]:[clip-path:polygon(_23%_0,_38%_0,_43%_7%,_57%_7%,_62%_0,_77%_0,_100%_20%,_83%_40%,_75%_33%,_75%_100%,_25%_100%,_25%_33%,_17%_40%,_0_20%_)] legacy:[.product-art-shirt_&]:w-[78%] legacy:[.product-art-shirt_&]:h-[72%] legacy:[.product-art-shirt_&]:rounded-[0] legacy:[.product-art-shirt_&]:mt-[0] legacy:[.product-art-shirt_&]:[padding-block:35px_15px] legacy:[.product-art-shirt_&]:[background:#b9dbea]',
    'legacy:[.product-art-print_&]:[background:#16495e] legacy:[.product-art-print_&]:text-[color:#d2eef3] legacy:[.product-art-print_&]:[border:8px_solid_#ece9e2] legacy:[.product-art-print_&]:rounded-[0] legacy:[.product-art-print_&]:mt-[0] legacy:[.product-art-print_&]:h-[76%]',
    'legacy:[.product-art-kit_&]:[background:#c9a488] legacy:[.product-art-kit_&]:text-[color:#382415] legacy:[.product-art-kit_&]:rounded-[4px] legacy:[.product-art-kit_&]:h-[52%] legacy:[.product-art-kit_&]:w-[70%] legacy:[.product-art-kit_&]:[transform:rotate(-8deg)] legacy:[.product-art-kit_&]:mt-[0]',
    'legacy:until-760:[&_>_span:first-child]:text-[length:14px]',
    'legacy:until-760:[&_small]:text-[length:5px]',
  ].join(' '),
  'reading-page': [
    'legacy:max-w-[750px]',
    'legacy:[&_h1]:text-[length:38px]',
    'legacy:[&_h2]:mt-[30px]',
    'legacy:[&_p]:text-muted',
    'legacy:until-760:[&_h1]:text-[length:32px]',
  ].join(' '),
  'reference-site': [
    '[&.reference-site]:text-home-text [&.reference-site]:[background:var(--home-page)] [&.reference-site]:overflow-clip',
    "[[data-theme='dark']_&.reference-site]:![background:var(--home-page)]",
    '[&.reference-site_:is(a,_button,_input,_select)]:[-webkit-tap-highlight-color:transparent]',
    '[&.reference-site_:is(button,_input,_select)]:min-h-11',
    '[&.reference-site_:is(a,_button,_input,_select):focus-visible]:[outline:2px_solid_var(--home-accent)] [&.reference-site_:is(a,_button,_input,_select):focus-visible]:outline-offset-[5px]',
    '[&.reference-site_:is(section,_[id])]:[scroll-margin-top:96px]',
    '[&.reference-site_svg]:shrink-0',
    '[&.reference-site_#categories]:![background:var(--home-elevated)] [&.reference-site_#categories]:border-home-line',
    '[&.reference-site_#categories_a]:rounded-[100px] [&.reference-site_#categories_a]:px-[18px] [&.reference-site_#categories_a]:min-h-11',
    "[&.reference-site_[aria-pressed='true']:not(.favorite-button)]:![background:var(--home-accent-soft)] [&.reference-site_[aria-pressed='true']:not(.favorite-button)]:!text-home-accent [&.reference-site_[aria-pressed='true']:not(.favorite-button)]:shadow-[inset_0_0_0_1px_color-mix(in_srgb,_var(--home-accent)_35%,_transparent)]",
    '[&.reference-site_footer]:[background:#080e16] [&.reference-site_footer]:pb-[100px] [&.reference-site_footer]:[border-top:1px_solid_#ffffff12]',
    '[&.reference-site_:is(.text-ink-900,_.text-ink-800,_.text-ink-700)]:!text-home-text',
    '[&.reference-site_:is(.text-ink-600,_.text-ink-500,_.text-ink-400)]:!text-home-muted',
    '[&.reference-site_:is(.text-primary-600,_.text-primary-700)]:text-home-accent',
    "[&.reference-site_:is(.bg-white,[class~='bg-white/95'],[class~='bg-white/90'])]:!bg-home-card",
    '[&.reference-site_:is(.border-ink-100,_.border-ink-200)]:!border-home-line',
    "[&.reference-site_:is([class~='text-white/50'],[class~='text-white/60'],[class~='text-white/55'])]:text-[color:#b7c5d5]",
    '[&.reference-site_:is(.bg-emerald-100,_.bg-sky-100,_.bg-rose-100,_.bg-primary-100)]:text-[color:#075985]',
    '[&_:is(article,_button,_a,_img)]:duration-[200ms]',
    '[&_article:hover]:[transform:translateY(-3px)] [&_article:hover]:[border-color:color-mix(in_srgb,_var(--home-accent)_35%,_var(--home-line))] [&_article:hover]:shadow-[0_8px_24px_#00000012]',
    '[&.reference-site_article_img]:transform-none',
  ].join(' '),
  'resale-ticket-art': [
    'flex items-center justify-center relative w-[92px] h-[72px] m-[0_0_22px_4px] text-[color:#84dcff] [border:1px_solid_#73d2ff70] rounded-[14px] [background:linear-gradient(135deg,_#23506a,_#112b40)] shadow-[7px_7px_0_#0b1422,_8px_8px_0_#4599c64d] [transform:rotate(-8deg)]',
    "[&::after]:[content:''] [&::after]:absolute [&::after]:right-[22px] [&::after]:top-2 [&::after]:bottom-2 [&::after]:[border-right:1px_dashed_#8cdcff60]",
    '[&_>_span]:absolute [&_>_span]:right-[-12px] [&_>_span]:bottom-[-10px] [&_>_span]:z-[1] [&_>_span]:p-[7px] [&_>_span]:text-[color:#a8eddf] [&_>_span]:[background:#183c3a] [&_>_span]:[border:1px_solid_#69cdb7] [&_>_span]:rounded-full',
  ].join(' '),
  'result-count': [
    'legacy:flex legacy:justify-between legacy:items-center legacy:min-h-8 legacy:text-[length:12px] legacy:text-muted legacy:m-[12px_0]',
  ].join(' '),
  'section-emblem': [
    'flex w-[46px] h-[46px] m-[14px_0_18px] items-center justify-center text-home-accent [background:var(--home-accent-soft)] [border:1px_solid_color-mix(in_srgb,_var(--home-accent)_25%,_transparent)] rounded-[14px] shadow-[0_0_28px_color-mix(in_srgb,_var(--home-accent)_6%,_transparent)] [margin-block:0_12px]',
    '[.chapter-resale_&]:hidden',
  ].join(' '),
  'section-heading': [
    'legacy:flex legacy:justify-between legacy:[align-items:end] legacy:gap-5 legacy:mb-6',
    'legacy:[&_h2]:text-[length:clamp(24px,_2.3vw,_31px)] legacy:[&_h2]:m-[7px_0_0] legacy:[&_h2]:leading-[1.25]',
    'legacy:until-760:[align-items:start] legacy:until-760:gap-3',
    'legacy:until-760:[&_h2]:text-[length:25px]',
    'legacy:[.export-home_&_h2]:text-[length:clamp(25px,_2.5vw,_34px)]',
  ].join(' '),
  'section-intro': [
    'legacy:text-muted legacy:text-[length:14px]',
    'legacy:[.export-home_.section-heading_&]:max-w-[630px] legacy:[.export-home_.section-heading_&]:m-[10px_0_0]',
  ].join(' '),
  selected: [
    'legacy:[.filter-tabs_button&]:[background:var(--accent-soft)] legacy:[.filter-tabs_button&]:text-accent legacy:[.filter-tabs_button&]:border-line legacy:[.filter-tabs_button&]:font-bold',
    'legacy:[.home-catalog_a&]:[background:var(--accent-soft)] legacy:[.home-catalog_a&]:text-accent legacy:[.home-catalog_a&]:border-line',
  ].join(' '),
  'site-footer': [
    'legacy:[border-top:1px_solid_var(--line)] legacy:[background:var(--surface)] legacy:pt-[45px]',
  ].join(' '),
  'site-header': [
    'legacy:sticky legacy:top-[0] legacy:z-[30] legacy:[background:var(--header)] legacy:[backdrop-filter:blur(18px)] legacy:[border-bottom:1px_solid_var(--line)]',
  ].join(' '),
  'skip-link': [
    'legacy:fixed legacy:top-[-100px] legacy:left-5 legacy:z-[100] legacy:[background:var(--surface)] legacy:p-[15px]',
    'legacy:[&:focus]:top-[15px]',
  ].join(' '),
  'snap-x': [
    '[.chapter-resale_&]:grid [.chapter-resale_&]:grid-cols-[repeat(3,_minmax(0,_1fr))] [.chapter-resale_&]:overflow-visible [.chapter-resale_&]:m-[0] [.chapter-resale_&]:p-[0]',
    'until-959:[.chapter-resale_&]:grid-cols-[1fr_1fr]',
    'until-639:[.chapter-resale_&]:grid-cols-[minmax(0,_1fr)]',
    'from-960:[.chapter-resale_&]:grid-cols-[repeat(2,_minmax(0,_1fr))]',
    '[.reference-site.reference-site_.chapter-resale_&]:flex [.reference-site.reference-site_.chapter-resale_&]:gap-5 [.reference-site.reference-site_.chapter-resale_&]:overflow-x-auto [.reference-site.reference-site_.chapter-resale_&]:p-[6px_2px_18px] [.reference-site.reference-site_.chapter-resale_&]:[scroll-snap-type:x_mandatory]',
  ].join(' '),
  'spotlight-body': [
    'p-5 min-w-0 flex flex-col gap-2.5',
    '[.spotlight-lead_&]:p-7 [.spotlight-lead_&]:gap-3.5',
    '[&_h3]:text-[length:18px] [&_h3]:font-extrabold [&_h3]:tracking-[-0.025em] [&_h3]:leading-[1.35] [&_h3]:text-home-text',
    'until-959:p-5 until-959:gap-3 until-959:flex-[1]',
    'until-959:[.spotlight-lead_&]:p-5 until-959:[.spotlight-lead_&]:gap-3 until-959:[.spotlight-lead_&]:flex-[1]',
    'until-639:[&_h3]:text-[length:22px]',
    '[.featured-hover-rail_&]:flex-[1] [.featured-hover-rail_&]:p-[18px]',
    '[.featured-hover-rail_&_h3]:text-[length:18px] [.featured-hover-rail_&_h3]:min-h-[49px]',
  ].join(' '),
  'spotlight-bottom': [
    'flex items-center justify-between gap-3 flex-wrap [border-top:1px_solid_var(--home-line)] pt-3.5 mt-[auto]',
    '[&_strong]:text-[length:19px] [&_strong]:whitespace-nowrap [&_strong]:text-home-text',
    '[.featured-hover-rail_&]:items-start [.featured-hover-rail_&]:gap-3',
    '[.featured-hover-rail_&_strong]:text-[length:18px]',
  ].join(' '),
  'spotlight-card': [
    'grid grid-cols-[150px_minmax(0,_1fr)] [background:var(--home-card)] [border:1px_solid_var(--home-line)] rounded-[20px] overflow-hidden [transition:transform_200ms_ease,_border-color_200ms_ease,_background_200ms_ease]',
    '[&:hover]:[transform:translateY(-3px)] [&:hover]:[background:var(--home-hover)] [&:hover]:[border-color:color-mix(in_srgb,_var(--home-accent)_45%,_transparent)]',
    'until-1199:grid-cols-[110px_minmax(0,_1fr)]',
    'until-959:flex until-959:flex-col',
    '[.featured-hover-rail_&]:flex [.featured-hover-rail_&]:flex-col [.featured-hover-rail_&]:flex-[1_1_0] [.featured-hover-rail_&]:min-w-0 [.featured-hover-rail_&]:will-change-[flex-grow,transform] [.featured-hover-rail_&]:[transition:flex-grow_720ms_cubic-bezier(0.22,_1,_0.36,_1),_transform_520ms_cubic-bezier(0.22,_1,_0.36,_1),_border-color_320ms_ease,_box-shadow_520ms_ease]',
    'pointer-wide-1100:[.featured-hover-rail:hover_&]:grow-[0.9]',
    'pointer-wide-1100:[.featured-hover-rail_&:hover]:grow-[1.32] pointer-wide-1100:[.featured-hover-rail_&:hover]:[transform:translateY(-5px)]',
    'pointer-wide-1100:[.featured-hover-rail_&:focus-within]:grow-[1.32] pointer-wide-1100:[.featured-hover-rail_&:focus-within]:[transform:translateY(-5px)]',
    'pointer-wide-1100:[.featured-hover-rail_&:hover_img]:[transform:scale(1.035)] pointer-wide-1100:[.featured-hover-rail_&:hover_img]:[transition:transform_760ms_cubic-bezier(0.22,_1,_0.36,_1)]',
    'until-1099:[.featured-hover-rail_&]:flex-[0_0_300px] until-1099:[.featured-hover-rail_&]:[scroll-snap-align:start]',
    'until-639:[.featured-hover-rail_&]:basis-[min(290px,_85vw)] until-639:[.featured-hover-rail_&]:min-w-0',
  ].join(' '),
  'spotlight-category': [
    'absolute left-3 bottom-3.5 [background:#08131de6] text-[color:#f7f8fa] text-[length:11px] p-[6px_10px] rounded-[30px] font-bold',
  ].join(' '),
  'spotlight-image': [
    'relative min-h-[190px] overflow-hidden',
    '[&_img]:w-full [&_img]:h-full [&_img]:object-cover [&_img]:absolute',
    '[.spotlight-lead_&]:min-h-[310px] [.spotlight-lead_&]:flex-[1]',
    'until-959:[.spotlight-lead_&]:min-h-[230px] until-959:[.spotlight-lead_&]:flex-[none]',
    'until-959:min-h-[230px] until-959:flex-[none]',
    'until-639:[.spotlight-lead_&]:min-h-[250px]',
    'until-639:min-h-[220px]',
    '[.featured-hover-rail_&]:flex-[none] [.featured-hover-rail_&]:min-h-[0] [.featured-hover-rail_&]:h-[225px]',
  ].join(' '),
  'spotlight-meta': [
    'flex items-center gap-[7px] text-home-muted text-[length:12px] leading-[1.6]',
    '[&_span]:overflow-hidden [&_span]:[text-overflow:ellipsis] [&_span]:whitespace-nowrap',
    '[&_svg]:text-home-accent',
    '[.featured-hover-rail_&]:text-[length:12px]',
  ].join(' '),
  'spotlight-status': [
    'flex items-center flex-wrap gap-2',
    '[&_>_span:last-child:not(:first-child)]:text-[length:11px] [&_>_span:last-child:not(:first-child)]:text-home-muted',
    '[.featured-hover-rail_&]:items-start [.featured-hover-rail_&]:flex-col',
  ].join(' '),
  'sr-only': [
    'legacy:absolute legacy:w-[1px] legacy:h-[1px] legacy:p-[0] legacy:m-[-1px] legacy:overflow-hidden legacy:[clip-path:inset(50%)] legacy:whitespace-nowrap legacy:border-0',
  ].join(' '),
  'text-[11px]': [
    'until-639:[.reference-site.reference-site_.home-chapter_&]:text-[length:12px]',
  ].join(' '),
  'text-button': [
    'legacy:inline-flex legacy:items-center legacy:gap-2.5 legacy:text-accent legacy:[font-weight:650] legacy:text-[length:13px] legacy:border-0 legacy:p-2 legacy:underline',
  ].join(' '),
  'text-ink-400': [
    "[[data-theme='dark']_&]:!text-[color:#89a4bd]",
    "[[data-theme='dark']_.navbar-shell.navbar-solid_&]:!text-[color:#89a4bd]",
  ].join(' '),
  'text-ink-500': ["[[data-theme='dark']_&]:!text-[color:#89a4bd]"].join(' '),
  'text-ink-600': [
    "[[data-theme='dark']_&]:!text-[color:#c5d7eb]",
    "[[data-theme='dark']_.navbar-shell.navbar-solid_&]:!text-[color:#c5d7eb]",
  ].join(' '),
  'text-ink-700': [
    "[[data-theme='dark']_&]:!text-[color:#c5d7eb]",
    "[[data-theme='dark']_.navbar-shell.navbar-solid_&]:!text-[color:#c5d7eb]",
  ].join(' '),
  'text-ink-800': ["[[data-theme='dark']_&]:!text-[color:#eef7ff]"].join(' '),
  'text-ink-900': [
    "[[data-theme='dark']_&]:!text-[color:#eef7ff]",
    "[[data-theme='dark']_.navbar-shell.navbar-solid_&]:!text-[color:#eef7ff]",
  ].join(' '),
  'text-link': [
    'legacy:inline-flex legacy:items-center legacy:gap-2.5 legacy:text-accent legacy:[font-weight:650] legacy:text-[length:13px]',
    'legacy:until-760:[.section-heading_&]:whitespace-nowrap legacy:until-760:[.section-heading_&]:text-[length:11px]',
  ].join(' '),
  'text-xl': ['[.reference-site.reference-site_article_&]:whitespace-nowrap'].join(' '),
  'text-xs': ['[.chapter-blog_article_&]:flex-wrap [.chapter-blog_article_&]:gap-2'].join(' '),
  'theme-control': ['relative text-[color:var(--home-text,_var(--text))] shrink-0'].join(' '),
  'theme-options': [
    'absolute right-[0] top-[calc(100%_+_10px)] min-w-[190px] p-[7px] z-[80] [border:1px_solid_var(--home-line,_var(--line))] rounded-[16px] [background:var(--home-card,_var(--surface))] shadow-[0_12px_40px_#0003]',
    '[&_button]:flex [&_button]:items-center [&_button]:w-full [&_button]:min-h-11 [&_button]:gap-2.5 [&_button]:p-[10px_12px] [&_button]:border-0 [&_button]:rounded-[10px] [&_button]:[background:transparent] [&_button]:text-[color:inherit] [&_button]:text-left [&_button]:text-[length:13px]',
    '[&_button_>_span]:flex-[1]',
    '[&_button:hover]:[background:var(--home-hover,_var(--surface-raised))]',
    '[&_button:focus-visible]:[background:var(--home-hover,_var(--surface-raised))]',
    "[&_button[aria-checked='true']]:text-[color:var(--home-accent,_var(--accent))] [&_button[aria-checked='true']]:[background:var(--home-accent-soft,_var(--accent-soft))]",
    'until-639:right-[-40px]',
  ].join(' '),
  'theme-trigger': [
    'flex items-center gap-[9px] min-h-11 p-[0_14px] [border:1px_solid_var(--home-line,_var(--line))] rounded-[24px] [background:var(--home-card,_var(--surface))] text-[color:inherit] text-[length:12px] font-bold cursor-pointer',
    '[&:hover]:[border-color:var(--home-accent,_var(--accent))]',
    "[&[aria-expanded='true']]:[border-color:var(--home-accent,_var(--accent))]",
    '[&_>_svg:last-child]:[transition:transform_180ms_ease]',
    "[&[aria-expanded='true']_>_svg:last-child]:[transform:rotate(180deg)]",
    'until-639:px-2.5 until-639:gap-1.5 until-639:text-[length:11px]',
  ].join(' '),
  'tickets-link': [
    'legacy:flex legacy:items-center legacy:gap-1.5',
    'legacy:until-1150:[&_span]:hidden',
    'legacy:until-760:[.header-actions_&]:hidden',
  ].join(' '),
  'tote-bag': [
    'legacy:relative legacy:flex legacy:flex-col legacy:justify-between legacy:w-[170px] legacy:h-[195px] legacy:mt-[45px] legacy:p-[23px] legacy:[background:#e9e1cd] legacy:text-[color:#244854] legacy:shadow-[15px_15px_35px_#182c3420,_inset_5px_0_7px_#0000000c] legacy:rounded-[3px_3px_25px_25px] legacy:[transform:rotate(-9deg)]',
    'legacy:[&_>_span:first-child]:text-[length:34px] legacy:[&_>_span:first-child]:tracking-[-0.06em] legacy:[&_>_span:first-child]:font-extrabold',
    'legacy:[&_small]:text-[length:9px] legacy:[&_small]:leading-[1.6] legacy:[&_small]:tracking-[0.13em]',
  ].join(' '),
  'tote-handle': [
    'legacy:absolute legacy:w-20 legacy:h-[95px] legacy:[border:12px_solid_#ded5bf] legacy:![border-bottom:0] legacy:rounded-[50%_50%_0_0] legacy:top-[43px] legacy:[transform:rotate(-9deg)]',
  ].join(' '),
  'tote-star': ['legacy:absolute legacy:bottom-5 legacy:right-5 legacy:text-[length:50px]'].join(
    ' ',
  ),
  'w-16': ['[.chapter-stars_&]:w-20 [.chapter-stars_&]:h-20'].join(' '),
  'xl:grid-cols-4': [
    'from-1024:[.chapter-discover_&]:grid-cols-[repeat(3,_minmax(0,_1fr))]',
    'from-1200:[.reference-site.reference-site_.chapter-discover_&]:grid-cols-[repeat(4,_minmax(0,_1fr))]',
  ].join(' '),
};
/** Expand dynamic component/state markers into their Tailwind utilities. */
export function ui(className: string): string {
  const result = new Set<string>();
  for (const token of className.split(/\s+/)) {
    if (!token) continue;
    result.add(token);
    for (const utility of (uiClasses[token] ?? '').split(/\s+/)) if (utility) result.add(utility);
  }
  return [...result].join(' ');
}
